<script>
 import { currentUser,isAuthenticated } from '$lib/stores/auth.js';
 import { subscription } from '$lib/stores/subscription.js';
 import { planLabel } from '$lib/product/navigation.js';
 import { authenticatedFetch } from '$lib/services/authenticated-fetch.js';
 let busy=false,failure='';
 async function portal(){busy=true;failure='';try{const res=await authenticatedFetch('/api/stripe/portal',{method:'POST'});const data=await res.json();if(!res.ok||!data.url)throw new Error(data.error||'No se pudo abrir la gestión de suscripción.');window.location.href=data.url;}catch(e){failure=e.message;}finally{busy=false;}}
</script>
<svelte:head><title>Mi cuenta · NioSports Pro</title></svelte:head>
<div class="product-page"><header class="product-heading"><div><span class="product-eyebrow">TU ESPACIO</span><h1>{$currentUser?.displayName||'Mi cuenta'}</h1><p>{$currentUser?.email||'Explora NioSports y crea una cuenta cuando quieras guardar tu actividad.'}</p></div><span class="product-badge">{$isAuthenticated?planLabel($subscription):'Sin sesión'}</span></header><div class="product-grid"><section class="product-panel"><h2>Tu acceso</h2><p>FREE abre los deportes y te permite conocer el análisis. Premium amplía las selecciones y herramientas disponibles.</p><a class="product-link" href="/pricing">Comparar planes ↗</a>{#if $isAuthenticated&&['pro','elite'].includes($subscription.plan)}<button class="product-action" disabled={busy} on:click={portal}>{busy?'Abriendo…':'Gestionar suscripción'}</button>{:else if !$isAuthenticated}<a class="product-action" href="/login">Iniciar sesión o crear cuenta</a>{/if}{#if failure}<p role="alert">{failure}</p>{/if}</section><section class="product-panel"><h2>Tu seguimiento</h2><a class="product-row" href="/bankroll"><span>Bankroll<small>Capital y exposición</small></span>↗</a><a class="product-row" href="/stats"><span>Mis estadísticas<small>Rendimiento de tus selecciones, no estadísticas de jugadores</small></span>↗</a><a class="product-row" href="/tracking"><span>Validación del modelo<small>Registro de pronósticos y resultados para revisión</small></span>↗</a><a class="product-row" href="/results"><span>Resultados<small>Revisar selecciones resueltas</small></span>↗</a></section></div><section class="product-section product-panel"><details><summary>Tu primera visita: cómo empezar</summary><ol><li>Abre Deportes y elige NBA o tenis.</li><li>Consulta un partido y revisa la fuente, las estadísticas y las limitaciones del análisis.</li><li>Usa Bankroll si quieres registrar y revisar tus decisiones.</li></ol><p class="product-note">Puedes explorar gratis. Consulta Cuenta para conocer tu plan; los ejemplos están identificados.</p></details></section><section class="product-section"><a class="product-link" href="/methodology">Metodología</a><a class="product-link" href="/legal/privacy">Privacidad</a><a class="product-link" href="/legal/responsible-gambling">Juego responsable</a></section></div>
