import { describe,it,expect } from 'vitest';
import { validateEdition,catalogView } from '../../src/lib/catalog/domain.js';
import { demoEdition } from '../../src/lib/catalog/demo.js';
export const now=Date.parse('2026-09-14T12:00:00Z');
export function edition(){return {version:1,isDemo:false,day:'2026-09-14',timezone:'America/Guayaquil',freePickId:'one',entries:['one','two','three'].map((id,i)=>({id,sport:i===1?'nba':'tennis',event:`A${i} · B${i}`,startsAt:'2026-09-14T20:00:00Z',tier:i===2?'free':'premium',modelVersion:'test-model',source:{name:'Verified provider',snapshotId:'a'.repeat(64),asOf:'2026-09-14T11:00:00Z'},analysis:{selection:`Private ${id}`,probability:.6,explanation:'Evidence recorded',factors:['Sample provided'],calibrated:false}}))};}
describe('server catalog authorization',()=>{
 it('explicit demo works throughout the day but can never be published',()=>{for(const instant of [now,Date.parse('2026-09-15T04:59:59Z')]){const data=demoEdition(instant);const view=catalogView(data,{now:instant,authenticated:true,allowDemo:true});expect(view.isDemo).toBe(true);expect(view.entries).toHaveLength(3);expect(view.entries.filter(e=>e.analysis)).toHaveLength(2);expect(()=>validateEdition(data,{now:instant,publishing:true,allowDemo:true})).toThrow();}});
 it('public previews never include Premium analysis or unlisted private fields',()=>{const data=edition();data.entries[1].secret='hidden';data.entries[1].analysis.secret='hidden';const view=catalogView(data,{now});expect(view.entries[0].analysis).toBeUndefined();expect(view.entries[1].analysis).toBeUndefined();expect(view.entries[2].analysis.selection).toBe('Private three');expect(JSON.stringify(view)).not.toContain('hidden');});
 it('FREE unlocks exactly the fixed daily reward and free content',()=>{const view=catalogView(edition(),{authenticated:true,plan:'free',now});expect(view.entries.filter(e=>e.tier==='premium'&&e.analysis).map(e=>e.id)).toEqual(['one']);expect(view.entries[1].locked).toBe(true);});
 it.each(['pro','elite'])('%s receives all available published analyses',plan=>{expect(catalogView(edition(),{authenticated:true,plan,now}).entries.every(e=>e.analysis)).toBe(true);});
 it('client plan claims alone do not grant access',()=>{expect(catalogView(edition(),{plan:'elite',now}).entries[0].analysis).toBeUndefined();});
 it('withdrawal removes the analysis without moving the free reward',()=>{const data=edition();const view=catalogView(data,{authenticated:true,now,withdrawals:[{entry_id:'one',reason:'New health information'}]});expect(view.freePickId).toBe('one');expect(view.entries[0].status).toBe('withdrawn');expect(view.entries[0].analysis).toBeUndefined();expect(view.entries[1].locked).toBe(true);});
 it('an earlier day cannot be replayed to collect more FREE picks',()=>{expect(catalogView(edition(),{authenticated:true,now:now+86400000}).entries[0].analysis).toBeUndefined();});
 it('does not mutate stored edition while filtering',()=>{const data=edition(),before=JSON.stringify(data);catalogView(data,{now});expect(JSON.stringify(data)).toBe(before);});
 it('rejects demos, started games, stale data and fabricated calibration on publish',()=>{for(const change of [d=>d.isDemo=true,d=>d.entries[0].startsAt='2026-09-14T06:00:00Z',d=>d.entries[0].source.asOf='2026-09-13T01:00:00Z',d=>d.entries[0].analysis.calibrated=true]){const data=edition();change(data);expect(()=>validateEdition(data,{now,publishing:true})).toThrow();}});
 it('rejects duplicate IDs and invalid probabilities',()=>{const data=edition();data.entries[1].id='one';expect(()=>validateEdition(data,{now})).toThrow();data.entries[1].id='two';data.entries[1].analysis.probability=NaN;expect(()=>validateEdition(data,{now})).toThrow();});
});
